[platformio]
default_envs = ears_nrf52840

[env:ears_nrf52840]
platform = nordicnrf52
board = nicenano
framework = arduino
monitor_speed = 115200
upload_port = COM17
monitor_port = COM17
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    fastled/FastLED @ ^3.9.14

[env:ears_receiver]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_port = COM17
monitor_port = COM17
monitor_dtr = 1
monitor_rts = 1
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    fastled/FastLED @ ^3.9.14

[env:ears_receiver_ota]
extends = env:ears_receiver
upload_protocol = espota
upload_port = 192.168.12.2041