name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ufbt
        run: pip install ufbt

      - name: Lint
        run: ufbt lint

      - name: Build
        run: ufbt
